### ISSUE TITLE
v0.3 - CI - Add Next.js Build Cache Persistence

### ISSUE THREAD

**Issue by huntharo** [pwrdrvr/microapps-core#259]
- Add build caching according to docs below
- https://nextjs.org/docs/advanced-features/ci-build-caching

```yaml
uses: actions/cache@v2
with:
  # See here for caching with `yarn` https://github.com/actions/cache/blob/main/examples.md#node---yarn or you can leverage caching with actions/setup-node https://github.com/actions/setup-node
  path: |
    ~/.npm
    ${{ github.workspace }}/.next/cache
  # Generate a new cache whenever packages or source files change.
  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
  # If source files changed but packages didn't, rebuild from a prior cache.
  restore-keys: |
    ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
```
